FROM golang:1.26.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux \
    go build -o /app/server ./cmd/api

FROM scratch

WORKDIR /app

COPY --from=builder /app/server /server
COPY --from=builder /app/config /app/config

EXPOSE 8080
ENTRYPOINT ["/server"]
